from __future__ import annotations

import pandas as pd
from pathlib import Path

from Predict.cartesian_predict import predict_cartesian
from Predict.config import DEFAULT_DATE


def main() -> None:
    riders = [
        "Dener Barbosa",
        "Josh Frost",
        "Alvaro Ariel",
        "Dalton Kasel",
        "Marcelo Procopio Pereira",
        "Jess Lockwood",
        "Rogerio Venancio",
        "Thiago Salgado",
        "Koltin Hevalow",
        "Elizmar Jeremias",
        "Luciano De Castro",
        "Joao Lucas Campos",
        "Leonardo Castro",
        "Cooper Davis",
        "Mason Taylor",
        "Lucas Divino",
        "Boudreaux Campbell",
        "Joao Ricardo Vieira",
        "Sandro Batista",
        "Eric Henrique Domingos",
        "Brody Robinson",
        "Dalton Krantz",
        "Jeferson Silva",
        "Macaulie Leather",
        "Braidy Randolph",
        "Bob Mitchell",
        "riquelmi Santos",
        "Miguel De Jesus",
        "Kaiden Loud",
        "Natanael Serra Aires",
        "Daniel Keeping",
        "Guilherme Valleiras",
        "Ezekiel Mitchell",
        "Chase Dougherty",
        "Colton Burkard",
        "Cort Mcfadden",
        "Heitor Santos Ferreira",
        "Daniel Feitosa",
        "Maverick Smith",
        "Brady Fielder",
        "Damiao Soares",
        "Vitor Losnake",
        "Murilo Henrique De Oliveira",
        "Alex Cerqueira",
        "Callum Miller",
        "Alisson De Souza",
        "Andrew Alvidrez",
        "Cody Jesus",
        "Alan De Souza",
        "Keyshawn Whitehorse",
        "Eduardo Aparecido",
        "Pokey Houghton",
        "Kyler Oliver",
        "Gustavo Luiz Da Silva",
        "Hudson Bolton",
        "Caden Bunch",
        "Ramon De Lima",
        "Jose Vitor Leme",
        "Adriano Salgado",
        "Eduardo Matos",
        "Dawson Branton",
        "Wingson Henrique Da Silva",
        "John Crimber",
        "Mauricio Gulla Moreira",
        "Felipe Furlan",
        "Everton Natan Da Silva",
        "Daylon Swearingen",
        "Winy Dos Santos",
        "Clay Guiton",
        "Tate Pollmeier",
        "Kase Hitt",
        "Jean Carlos Teodoro",
        "Derek Kolbaba",
        "Yan Victor Cunha",
        "Jacauy Hale",
        "Jett Harkins",
        "Ethan Winckler",
        "Sage Kimzey",
        "Joao Henrique Lucas",
        "Kaique Pacheco",
        "Qynn Andersen",
        "Julio Cesar Marques",
        "Austin Richardson",
        "Pablo Soares",
        "Cassio Dias",
        "Trace Redd",
        "Marco Rizzo",
        "Claudio Montanha Jr.",
        "Anderson De Oliveira",
        "Paulo Eduardo Rossetto",
        "Boston Leather",
        "Grayson Cole",
        "Bruno Carvalho",
        "Elzisclay Dos Santos",
        "Andrei Scoparo",
        "Ednelio Rodrigues",
        "Maikon Calixton Rocha",
        "Casey Roberts",
        "Ramon Fiorini",
        "Ramon Fiorini de souza",
        "Trey Holston",
        "Jhon Carlos Moreira",
        "Flavio Zivieri",
        "Alison Dos Santos",
        "Romario Leite",
        "Cannon Cravens",
        "Colton Byram",
        "Vinicius Rodrigues Pereira",
        "Afonso Quintino",
        "Vinicius Pinheiro Correa",
        "Hudson Frey",
        "Conner Halverson"

    ]

    bulls = [
        "Y69 Bandito Bug",
        "Y1 Tigger",
        "X71 Bad Intentions",
        "X41 Hookie Monster",
        "X26 Real Deal",
        "W800 Punchy Pete",
        "W150 Pay Pal",
        "S827 Hoka Hey",
        "S130 White Out",
        "RD915 Creek",
        "R62 UTZ BesTex Smokestack",
        "P829 Rafter P Construction's Smooth Over It",
        "P15 Play Time",
        "N11 The Kraken",
        "101 Boot Barn's Skunk Kitty",
        "L7 Live Bait",
        "K50 Elmo",
        "K46 Jailor",
        "K25 Riser",
        "K03 Murrell",
        "J804 Fire Kat",
        "J79 Ridin' Dirty",
        "J740 Rafiki",
        "J44 Cherry Shot",
        "J39- Ransom",
        "J38 Sour Patch",
        "J29 Greasy Bend",
        "J2 Reality Check",
        "J17 Red Velvet",
        "J1 Pearl Snap",
        "J02 Mike Honcho",
        "I17 Ridin' Salty",
        "I11 Moonlight Graham",
        "H94 Big Lean",
        "H9 Holy Roller",
        "H604-1 Phantom",
        "H27 Lift Me Up",
        "H2-3 Always Been Crazy",
        "H15 Slick Rick",
        "H10 Flossin",
        "H09 Magic Boss",
        "H07 Pac Man",
        "H06 Dana White's Playmate",
        "H05 Calhoun Oil",
        "H04 Red Hot",
        "G34 DirtyBru",
        "G15 Snap Chatter",
        "G08 Smoke Down",
        "F51 Mr. Bojangles",
        "F15 Socks In A Box",
        "D10 Cooter Brown",
        "922 Sly",
        "527 Preachers Kid",
        "C43 Strapper",
        "C363 Red Popcorn",
        "023 Living On A Prayer",
        "J65 Best Bet",
        "936 Mala Madre",
        "931 Sugar Bear",
        "B82 Primo",
        "B2113 White Command",
        "B10 Gravedigger",
        "080 Catching Gears",
        "035 New Dinero",
        "A141 Pneu-Dart's Chief Wahoo",
        "9X5 Rip Tide",
        "9X Dark Thoughts",
        "9C Nobody",
        "988 Coal Train",
        "980 Mighty Mouse",
        "979 Fringe Minority",
        "977 Wild Fire",
        "975 Reuben",
        "97 The Raven",
        "963J Big Bills",
        "963 Doze You Down",
        "960 Cash Goblin",
        "96 Bangarang",
        "95J Alakazoo",
        "959 Lever Action",
        "956 Radical Dude",
        "955 Top Dollar",
        "953 July",
        "95 Barbarosa",
        "94H Late Night Toss",
        "949 Smokin' Joe",
        "-949 Puckered Up",
        "948 Black Harbor",
        "941 Buckaroo",
        "9406 Honky Tonk",
        "938 Stone Cold",
        "932 Desert Twister",
        "931 Big Red Train",
        "930 Umm",
        "928 Finger Roll",
        "927 Boot Barn's Sandman",
        "925 Sky Walker",
        "925 Hunting Trip",
        "924 Red Dirt",
        "923 Ghost Face",
        "921 Johnny Rocket",
        "920 Snuggles",
        "920 BRUNT Haymaker",
        "92 Hoobastank",
        "919 Kodiac",
        "918 Down Payment",
        "917 Peterbilt",
        "916 Chico",
        "915 Bex Red Eye",
        "914 Mo Money",
        "914 Badlands",
        "913 Windy",
        "910 Money Moves",
        "91 Washita Red",
        "90J Prince Charming",
        "909 War Boy",
        "909 Money Pit",
        "907 Dirty Deeds",
        "906 In My Blood",
        "904 Cash On Black",
        "904 Bomb Diggity",
        "901 The Gambler",
        "9 Eyes On Me",
        "8X2 Dang, Dang",
        "89H Buck Nasty",
        "898 Simon",
        "894 Tijuana Two-Step",
        "891F Testified",
        "8-9 Joe Cool",
        "87H Tip It",
        "877 Exodus",
        "876 Swamp Donkey",
        "85J Peanut",
        "8518 Pneu Dart's Gold Standard",
        "84J Fat Lip",
        "8455 Wild Card",
        "83J Hold On Loosely",
        "8383 Dirty Dave",
        "834F Still Flyin' Crazy",
        "829 Ugly This",
        "824 EmmDee",
        "-822 Air Marshall",
        "821 Soul Train",
        "820 Feeds Red River",
        "82 Wingnut",
        "81K Achilles",
        "8194 Blue Duck",
        "819 American You",
        "816 Bad Bob",
        "8157 Skippy",
        "814 Tulsa Time",
        "814 Boss Hoggin",
        "813 Crazy Party",
        "80G Jam Jam",
        "808 Miller Time",
        "-806 Lari's Speck",
        "804 Ace",
        "802 Vanilla Bean",
        "80 Whiplash",
        "7J Chicken In Black",
        "792 Red Headed Stranger",
        "781 Uncle Rico",
        "77 Cowboy Tuxedo",
        "766 Gaucho",
        "76 Sneaky Situation",
        "748 The Jungle",
        "74 Jokers Misfit",
        "73H Moving On",
        "727 Grey Fox",
        "723 Mike's Motive",
        "720 Red Light",
        "716 Outlaw",
        "715 Twisted Sister",
        "712 No Doubt",
        "710 Do Dat Eddie",
        "71 Kill Switch",
        "70J Uncle Pete",
        "70H Stryker",
        "704J Hot 'n Spicy",
        "703 Hit or Miss",
        "701 Magic Potion",
        "7003 Bueno",
        "7- Say When",
        "7 Pillow Talk",
        "6X129 Iron Banana",
        "6F Tchoupitoulas",
        "693Y JL Gray's Ground Pounder",
        "68 Oreo",
        "67H American Made",
        "67F El Chapo",
        "678Z Home Slice",
        "67 Benjamin Ranklin",
        "67 American Hustle",
        "666 Nefarious",
        "65F Lone Star",
        "659 Slingin' It",
        "64 Velvet Revolver",
        "639 The Undertaker",
        "637D Border Crisis",
        "626 Chateau Montelena's Montana Jacket",
        "61G Big Timber",
        "615 The Black",
        "61 Redneck",
        "60J Punchy",
        "60J Cutting Edge Sugar Daddy",
        "60/1 Wild Country",
        "58H Ruckus",
        "56J Sherk",
        "569G Rogue One",
        "567 Body Roc",
        "55 Nickleback",
        "55 J Lazy S",
        "53G Hard Candy",
        "511 Holdin My Own",
        "50J Sweet Action",
        "500 I'm Legit Too",
        "49G Ah Hell",
        "498 Sharp Shooter",
        "497 Henry",
        "48J Last Call",
        "47J Vindicated",
        "41K Go Blue",
        "41J Mr. Jimmy",
        "411 Minds Broke",
        "41 Spectacular",
        "40J Uncle Billy",
        "405 Heavy Load",
        "40 Smokey",
        "-4 SPM",
        "4 Malibu's Top Dawg",
        "4 Bucking Bill",
        "3H Landman",
        "3G Frank",
        "38J Blowhard",
        "38H- War Wagon",
        "38 38 Special",
        "37H Electric Kitty",
        "379 Hey Jack",
        "36J Oyster Creek Brawler",
        "36 Rockville",
        "33H- Little Country",
        "3371 Mustache Man",
        "32G Zapata",
        "322 Show Me Dollars",
        "321 King Tut",
        "320 Rock 'n Roll",
        "31J Body Bag",
        "31H Bullistic",
        "31G Army Slasher",
        "31 War Paint",
        "30H Happy Hour",
        "301 Half Cocked",
        "2X Blackstone",
        "2K Dirty Bomb",
        "2H Pepperoni",
        "29G Hard Core Slinger",
        "292 Squealer",
        "28 Shy Pete",
        "27J Yo Mamma",
        "273 Rocket Man",
        "27 Hillbilly Heat",
        "269 Red Ant",
        "25-K Simple Man",
        "25H Nervous Hospital",
        "25g Bon Jovi",
        "258 Tropic Thunder",
        "258 Float And Sting",
        "24J Snappy",
        "24J Lieutenant Dan",
        "247 Pegasus",
        "244 Nasubi",
        "239 Sir Lion",
        "23 Toad",
        "23 I'm Him",
        "22J Average Joe",
        "228Z Show Me The Money",
        "2263 Mojo",
        "2246 Felix",
        "2236 Blister",
        "22-2 Nachos",
        "2201 Loaded Question",
        "220 Bullicous",
        "219 Cookie",
        "2165 Buck",
        "2162 Blonde Bomber",
        "2137 Dynamite",
        "2127 Pay Dirt",
        "21-20 Mississippi Mercenary",
        "2114 Where's the Beef",
        "2114 Easy Labor",
        "2110 Hay Train",
        "211 Triton",
        "2105 Mouse Trap",
        "2102 Big Jake",
        "2101 Question This",
        "21 Lights Out",
        "2099 Muddy Jake",
        "2096 Sizmagraf",
        "209 Nakatosh Nation",
        "207 Wicked Solo",
        "-205 Hermes",
        "2041 Lock 'n Load",
        "203 Caesar",
        "202K Boot Money",
        "2020 Bruce",
        "2016 Peanut",
        "2015 Smack Ya",
        "2015 Business Man",
        "201 Organize Chaos",
        "2003 Red Bull",
        "2001 Trash Panda",
        "2001 Mr. Man",
        "20 TNT",
        "1J Warlock",
        "1J The Intimidator",
        "1H Fatal Attraction",
        "19H Man Hater",
        "197 Bookers Bandit",
        "194 Dixie Flash",
        "192 Snoop Dog",
        "191 Barstool",
        "1904 Bone Digger",
        "190 Horizons Creedmoor",
        "19 Amarillo Highway",
        "18K Kippers Rippers",
        "189 Kung Fu Panda",
        "185J Kiowa Havoc",
        "185 Noslaw Extrasauce",
        "1846 Diablo",
        "182J Plowboy",
        "1822 Fajita",
        "182 Black Tie",
        "181 Turning Point",
        "-18- Smackdown",
        "17L Gucci Flip Flops",
        "17J Torched",
        "17G Hector",
        "177 Cutter",
        "1766 Power Trip",
        "176 Bosco",
        "1757 Another Round",
        "1747 Napoleon",
        "174 Squealin' Kitty",
        "1735 Boomerang",
        "1726 Whip",
        "17 Constant Payne",
        "-17 Buffalo Heifer",
        "16K Fire Fight",
        "16J Herded.com The Gambler",
        "1660 Nacho Night",
        "165 Milestone",
        "164 Raider",
        "162 Drago",
        "161J Big Shasta",
        "161H Abracadabra",
        "16 Pinecone",
        "16 Iceberg Slim",
        "16 Damaged Goods",
        "15X Project X",
        "15E Red Mosquito",
        "156 Trigger Happy",
        "156 Ronnie Two Times",
        "14J Walk Hard",
        "14H Rombauer",
        "147 Dozier",
        "14-6 John 14:6",
        "145 Magic Hunter",
        "145 Lazarus",
        "144 High Road",
        "144 Blue Silhouette",
        "143 Good Riddance",
        "14 Interstate Daydream",
        "13H Sucker Pop",
        "139 Foolish Pride",
        "137 Demonic",
        "135 Itchy Scratchy",
        "133H WinRocks Headache",
        "131 Feel the Magic",
        "12K Uncle Adam",
        "12-K Head Turner",
        "129 NashVegas",
        "129 Cramer",
        "128J The Player",
        "128J Love County",
        "128 Smores",
        "127 Lap Dancer",
        "1257 Zorro",
        "124 Holy Shift",
        "123 True Grit",
        "123 Short Fire",
        "122J Josey Wales",
        "122 Lost In The Sauce",
        "122 Doctor Win",
        "1211 Hail Mary",
        "121 Judgement Day",
        "121 Bam Bam",
        "120J Pacifico",
        "120 Smooth Violation",
        "12 Rorschach",
        "12 Gunsmoke",
        "11k Wavy Bomb",
        "119 Soul Man",
        "1170 Big X",
        "116 Stacks",
        "115 Nine Lives",
        "115 Night Agent",
        "1140 Karla's Pure Country",
        "-114 Night Prowler",
        "114 I'm a Hostage",
        "113 High Caliber",
        "113 Blue Nerve",
        "112 Halo",
        "111 Mystified",
        "1101 Wicked In a Winning Way",
        "110 Cherry Chew",
        "110 Black Velvet",
        "11 Triple Cross",
        "109 Uncorked",
        "109 Purple Rain",
        "106J Kevin",
        "106 Unhinged",
        "106 Scrappy",
        "106 Not Like Us",
        "106 Darkside",
        "104J Coach",
        "103H I'll Make Ya Famous",
        "103 Chili Mango",
        "102J Hard Eight",
        "102J Gold Buckle",
        "102 Jeter",
        "102 Cracky Chan",
        "101 Sober Child",
        "101 Boot Barn's Skunk Kitty",
        "100 Mr. Koolie",
        "099 Shot Caller",
        "086 Brett's Silver Eagle",
        "0816 Smoke Show",
        "07G Baldy",
        "076 Toxic Masculinity",
        "071H Apple Juicing",
        "070 Cajun Brute",
        "07 Night Fury",
        "07 Irish Car Bomb",
        "07 Bucktown",
        "069 Snow Day",
        "066 Ruthless",
        "065J Uncle Doc",
        "061 M.A.C.A.",
        "061 Lansky",
        "0601 Let Him Fly",
        "06 The Paint",
        "05J Self Made",
        "056 Sweet John",
        "055 Santana",
        "054 Levy",
        "053 Ares",
        "04-K Shank",
        "0498 Long Gone",
        "048 Rank Hank",
        "041 Big Red",
        "041 Big Mac",
        "04 Mr Teller",
        "04 Midnight Blues",
        "039 There's Your Sign",
        "035 Woody",
        "035 Hay Ring",
        "034 Scooter Tooter",
        "033 Smokey",
        "030 Whoa",
        "030 Real Western",
        "029H What's Poppin",
        "029 UB Smooth",
        "026 Let's Roll",
        "024 Wild Child",
        "024 L.A.",
        "023 Gas Money",
        "021J Big Man",
        "021 Gone Rogue",
        "020 Rowdy",
        "019 Old Testament",
        "0182 Workin' Man",
        "017 Swirl Your Glass",
        "017 OptiWize Mercy",
        "0160 Level Up",
        "016 Fire Zone",
        "015 Ezra The Great",
        "014 Milestone",
        "012H Sunrise",
        "012 Crime Scene",
        "011 Jonah Hex",
        "011 Designated Survivor",
        "011 Boot Barn's Tyrone",
        "01 The One",
        "009 Margin of Error",
        "008 Rip",
        "008 Cockeye",
        "007 The Don",
        "005 Unhinged",
        "004 Schliterbahn",
        "003 Slingin Tubs",
        "003 Bad Boy",
        "0021 Goin' Solo",
        "002 I Hate You",
        "001 PIF",
        "001 Nightmare",
        "001 Boot Barn's Pack Rat",
        "000 Triple Aught",
        "00 Gizmo",


    ]

    print("Running cartesian predictions...")
    print(f"Riders: {len(riders)} | Bulls: {len(bulls)} | Total: {len(riders) * len(bulls)}")
    df = predict_cartesian(riders, bulls, event_date=DEFAULT_DATE, mode="auto")

    if df.empty:
        print("No predictions returned.")
        return

    print("Top results:")
    print(df.head(10).to_string(index=False))

    out_path = Path("batch_cartesian.xlsx")
    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name="Predictions", index=False)
    print(f"Saved predictions to {out_path.resolve()}")


if __name__ == "__main__":
    main()


